import React, { useState } from 'react';
import './FAQ.css';

const FAQ = ({ type = 'home' }) => {
  const faqData = {
    home: [
      {
        q: "What is deepfake detection?",
        a: "Deepfake detection is the process of identifying AI-generated or digitally manipulated content—like fake images, videos, or voices—that are made to look and sound real. These are created using neural networks to mimic real people. TruthLens AI uses forensics to scan for pixel-level anomalies, compression patterns, and vocal spectral details."
      },
      {
        q: "How does the image detector work?",
        a: "TruthLens AI processes uploaded images through a series of tests: Error Level Analysis (ELA) to find splicing, Laplacian filter variance to detect skin anomalies, and metadata audits to locate known generator parameters."
      },
      {
        q: "Is TruthLens AI completely free?",
        a: "Yes, our web application is free to use. There are no credit cards required, no hidden paywalls, and no subscription packages."
      },
      {
        q: "Is my uploaded content private?",
        a: "Yes. Your privacy is our highest priority. Uploaded media is processed directly in memory to run the detection model and is not saved or retained on our disks."
      }
    ],
    image: [
      {
        q: "What is deepfake image detection?",
        a: "It is the process of using AI to determine if an image has been generated by tools like Stable Diffusion, Midjourney, DALL-E, or manipulated using local edits. It scans for lighting inconsistencies, noise distribution shifts, and EXIF metadata markers."
      },
      {
        q: "Is the image deepfake detector 100% accurate?",
        a: "No detector is perfect, but TruthLens AI uses a multi-layered verification system (ELA, face skin variance, noise levels, frequency analysis) that yields highly accurate results."
      },
      {
        q: "What image formats are supported?",
        a: "We support standard image formats: PNG, JPG, JPEG, and WEBP files up to 10MB."
      }
    ],
    video: [
      {
        q: "How does video deepfake detection work?",
        a: "We extract up to 15 frames from the video. Each frame is analyzed using deep neural networks to detect facial abnormalities. We also run inter-frame checks to catch sudden color/brightness changes and track face jitter."
      },
      {
        q: "What video formats can I upload?",
        a: "You can upload MP4, MOV, and WEBM video clips up to 50MB in size. We analyze the first 3 minutes of the clip."
      },
      {
        q: "Can this detect real-time video streams?",
        a: "Currently, our tool operates on file uploads. Real-time API integrations are supported for developer self-hosting setups."
      }
    ],
    audio: [
      {
        q: "How does voice clone detection work?",
        a: "Voice clone detection extracts MFCC and pitch (F0) profiles from the audio. Because voice generators produce speech mathematically, cloned voices have unnaturally flat pitch envelopes and mathematically uniform pause timings."
      },
      {
        q: "What audio formats are supported?",
        a: "We support MP3, WAV, OGG, and FLAC audio files up to 20MB."
      },
      {
        q: "Can it recognize multiple cloned voices in a conversation?",
        a: "The audio analyzer checks the entire spectral profile of the file. If synthetic voice components are mixed with natural human speech, the spectral consistency audits will flag the anomalies."
      }
    ]
  };

  const activeFaqs = faqData[type] || faqData.home;
  const [openIndex, setOpenIndex] = useState(null);

  const toggleFAQ = (idx) => {
    setOpenIndex(openIndex === idx ? null : idx);
  };

  return (
    <section className="faq-section container">
      <div className="features-header left-aligned-section">
        <div className="section-stamp">Common Queries</div>
        <h2>FREQUENTLY ASKED QUESTIONS</h2>
        <p>
          Get quick answers on how TruthLens AI handles media analysis, accuracy, and data security.
        </p>
      </div>

      <div className="faq-list">
        {activeFaqs.map((item, idx) => (
          <div key={idx} className={`glass-card faq-item ${openIndex === idx ? 'open' : ''}`}>
            <button className="faq-question-btn" onClick={() => toggleFAQ(idx)}>
              <span>{item.q}</span>
              <span className="faq-arrow">{openIndex === idx ? '▲' : '▼'}</span>
            </button>
            <div className="faq-answer">
              <p>{item.a}</p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
};

export default FAQ;
